- name: install symfony installer
  shell: curl -LsS https://symfony.com/installer -o /usr/local/bin/symfony
  become: yes
  
- name: symfony installer chmod
  shell: chmod a+x /usr/local/bin/symfony
  become: yes
  
  
#- name: Create project
#  shell: symfony new {{ SymfonyProjectName }}
#  args:
#    chdir: /var/www
#    creates: /var/www/{{ SymfonyProjectName }}
#  become: yes

